services:
  manager:
    image: crack-hash-manager:latest
    ports:
      - 8090:8090
    networks:
      - crack
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker1:
    image: crack-hash-worker:latest
    networks:
      - crack
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker2:
    image: crack-hash-worker:latest
    networks:
      - crack
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker3:
    image: crack-hash-worker:latest
    networks:
      - crack
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  worker4:
    image: crack-hash-worker:latest
    networks:
      - crack
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - crack

  mongodb-primary:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--quiet", "--logpath", "/dev/null"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb-primary:27017',priority:1},{_id:1,host:'mongodb-replic1:27018',priority:0.5},{_id:2,host:'mongodb-replic2:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 20s
      retries: 20
    ports:
      - 27017:27017
    volumes:
      - mongodb1_data:/data/db
    networks:
      - crack
    logging:
      driver: none

  mongodb-replic1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27018:27018
    volumes:
      - mongodb2_data:/data/db
    networks:
      - crack
    logging:
      driver: none

  mongodb-replic2:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--quiet", "--logpath", "/dev/null"]
    ports:
      - 27019:27019
    volumes:
      - mongodb3_data:/data/db
    networks:
      - crack
    logging:
      driver: none

volumes:
  mongodb1_data:
  mongodb1_config:
  mongodb2_data:
  mongodb2_config:
  mongodb3_data:
  mongodb3_config:
  worker1:
  worker2:

networks:
  crack:
    name: crack
    driver: bridge

