manager:
  alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  workers-count: 4

server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://mongodb-primary:27017,mongodb-replic1:27018,mongodb-replic2:27019/crack-hash?authSource=admin&replicaSet=rs0

  rabbitmq:
    username: user
    password: password
    host: rabbitmq
    port: 5672
