manager:
  alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  part-count: 4

server:
  port: 8090

spring:
  rabbitmq:
    username: user
    password: password
    host: rabbitmq
    port: 5672

  data:
    mongodb:
      uri: mongodb://mongo-primary:27017,mongo-replic1:27018,mongo-replic2:27019/crack-hash?authSource=admin&replicaSet=crack-hash
